# This is human-readable name which will be used everywhere in UI.
name: Hrvatski
# Indicates if the locale uses Right-to-Left writing.
rtl: false
# Locale name which will be passed into PHP's setlocale function.
time_locale: hr_HR.UTF8
# Various formats which will be used with PHP's strftime function.
date_format:
    full: "%d.%m.%Y %H:%M"
    date: "%d.%m.%Y"
    time: "%H:%M"
